# Generated by Django 5.1.1 on 2025-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
