# Generated by Django 5.1.1 on 2025-11-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='inventory.product')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bundles', to='inventory.product')),
            ],
        ),
    ]
