# Generated by Django 5.1.1 on 2025-11-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_bundle_component_delete_bundlecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='inventory.product', unique=True),
        ),
    ]
