# Generated by Django 5.1.1 on 2025-11-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_bundle_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product_specification',
            field=models.CharField(blank=True, default='Specification', max_length=255, null=True),
        ),
    ]
