# Generated by Django 5.1.1 on 2025-11-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_report_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='product_specification',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
