# Generated by Django 5.1.1 on 2025-11-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_report_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
