# Generated by Django 5.1.1 on 2025-11-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_report_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='product_specification',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
