# Generated by Django 5.1.1 on 2025-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_orderlog_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order_date',
            field=models.DateField(),
        ),
    ]
