# Generated by Django 5.1.1 on 2025-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_report_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
