# Generated by Django 5.1.1 on 2025-11-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_report_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='product_bundle',
            field=models.BooleanField(default=False),
        ),
    ]
