# Generated by Django 5.1.1 on 2026-01-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_orderlog_product_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformaCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='User', max_length=255, null=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaPerforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('No Receipt', 'No Receipt')], default='Receipt', max_length=255, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('number_of_items', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, default='User', max_length=255, null=True)),
                ('customer_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performas', to='inventory.performacustomer')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='Product', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, default='Pcs', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('performa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.performaperforma')),
            ],
        ),
    ]
